-- DROP ANY TABLES CREATED IN THE UP SCRIPT
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS zones;
DROP TABLE IF EXISTS sensors;
DROP TABLE IF EXISTS sensor_data;
DROP TABLE IF EXISTS strain;
DROP TABLE IF EXISTS plant_status;
DROP TABLE IF EXISTS plant;
DROP TABLE IF EXISTS plant_status_log;
DROP TABLE IF EXISTS plant_note;
DROP TABLE IF EXISTS metric;
DROP TABLE IF EXISTS plant_measurements;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS plant_activity;


